# Generated by Django 3.2.9 on 2021-11-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('content', models.TextField(blank=True, max_length=155, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
